spring.datasource.url=jdbc:postgresql://localhost:5432/wayfarer
spring.datasource.username=postgres
spring.datasource.password=wayfarerPassword

spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
spring.jpa.hibernate.ddl-auto=update